<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25520" started-at="2018-01-01T07:32:57Z" finished-at="2018-01-01T07:33:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25520" started-at="2018-01-01T07:32:57Z" finished-at="2018-01-01T07:33:22Z">
      <class name="c2info_OrderBuk_DashboardTCs.TC_001_VerifyAllBucketLinks">
        <test-method status="PASS" signature="setup()[pri:0, instance:c2info_OrderBuk_DashboardTCs.TC_001_VerifyAllBucketLinks@61009542]" name="setup" is-config="true" duration-ms="7536" started-at="2018-01-01T13:02:57Z" finished-at="2018-01-01T13:03:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:c2info_OrderBuk_DashboardTCs.TC_001_VerifyAllBucketLinks@61009542]" name="beforeMethod" is-config="true" duration-ms="3" started-at="2018-01-01T13:03:04Z" finished-at="2018-01-01T13:03:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void c2info_OrderBuk_DashboardTCs.TC_001_VerifyAllBucketLinks.verifyAllBucketlinks() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyAllBucketlinks()[pri:0, instance:c2info_OrderBuk_DashboardTCs.TC_001_VerifyAllBucketLinks@61009542]" name="verifyAllBucketlinks" duration-ms="17682" started-at="2018-01-01T13:03:04Z" finished-at="2018-01-01T13:03:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please fill the following fields to login] but found [Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please fill the following fields to login] but found [Login]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at c2info_OrderBuk_DashboardTCs.TC_001_VerifyAllBucketLinks.verifyAllBucketlinks(TC_001_VerifyAllBucketLinks.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAllBucketlinks -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:c2info_OrderBuk_DashboardTCs.TC_001_VerifyAllBucketLinks@61009542]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-01-01T13:03:22Z" finished-at="2018-01-01T13:03:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyAllBucketlinks status=FAILURE method=TC_001_VerifyAllBucketLinks.verifyAllBucketlinks()[pri:0, instance:c2info_OrderBuk_DashboardTCs.TC_001_VerifyAllBucketLinks@61009542] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:c2info_OrderBuk_DashboardTCs.TC_001_VerifyAllBucketLinks@61009542]" name="endTest" is-config="true" duration-ms="282" started-at="2018-01-01T13:03:22Z" finished-at="2018-01-01T13:03:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- c2info_OrderBuk_DashboardTCs.TC_001_VerifyAllBucketLinks -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
